# ASP.NET Core (.NET Framework)
# Build and test ASP.NET Core projects targeting the full .NET Framework.
# Add steps that publish symbols, save build artifacts, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
- main

pr:
  branches:
    include:
    - main

pool:
  vmImage: 'windows-latest'

variables:
  solution: '*.sln'
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'
  workingDirectory: '.'

stages:
- stage: build
  jobs:
  - job: build
    pool:
      vmImage: 'windows-latest'
    steps:
    
    - task: NuGetToolInstaller@1

    - task: NuGetCommand@2
      inputs:
        restoreSolution: '$(solution)'

    - script: dotnet build --configuration Release
      displayName: dotnet build
      workingDirectory: $(workingDirectory)

    - script: dotnet test --configuration Release
      displayName: dotnet test
      workingDirectory: $(workingDirectory)
